permissions:
    id-token: write # This is required for requesting the JWT
name: sample-secret-retrieval 
run-name: ${{ github.actor }} is getting secrets :)
on: [push]
jobs:
  get-secret:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch Infisical Secrets
        uses: Infisical/secrets-action@v1.0.16
        with:
          method: "oidc"
          identity-id: "f7b28d8b-ac19-4d6c-96d3-7e80581c5f69"
          env-slug: "Development"
          project_slug: "nico-corrarello-superday-zz-io"
      - name: "Show env vars"
        run: env
